name: Checkmarx-Pull-Request-Scan

on:
  pull_request:
    branches:
      - master
      #- main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2
      # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5 # GitHub Action version
        with:
          project: ${{ github.event.repository.name }}  # <-- Insert Checkmarx CxSCA Project Name
          # team: /CxServer/media-and-entertainment/data-mesh/aws-marketing # <-- Make sure to use fwd slashes / and enclose the team name in single quotes (')
          # preset: ASA-Premium
          # checkmarx_url: https://itv.checkmarx.net
          # checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }} # Define this in your GitHub repo secrets as the name you set for your checkmarx service account
          # checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # Define this in your GitHub repo secrets as the password you set for your checkmarx service account
         #  checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C  # gitleaks:allow
          break_build: true
          incremental: true
          sca_api_url: https://eu.api.scacheckmarx.com
          sca_app_url: https://eu.sca.scacheckmarx.com
          sca_access_control_url: https://eu.platform.checkmarx.net
          sca_tenant: EU-Support
          sca_username: ${{ secrets.SCA_USERNAME }} # Define this in your GitHub repo secrets as the name you set for your checkmarx service account
          sca_password: ${{ secrets.SCA_PASSWORD }} # Define this in your GitHub repo secrets as the password you set for your checkmarx service account
          bug_tracker: GITHUBPULL # This will create a report on your pull requests
          params: --sca.team=${{ env.CHECKMARX_TEAM }} --checkmarx.settings-override=true --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --checkmarx.cx-branch=true --repo-url="https://github.com/$GITHUB_REPOSITORY" --merge-id=${{ github.event.number }} --logging.level.com.checkmarx.flow.service=DEBUG --logging.level.com.checkmarx.flow.utils=DEBUG --logging.level.com.checkmarx.sdk.service=DEBUG --sca.thresholds-Severity.HIGH = 7
